[toolchain]
moc = "1.4.1"

[dependencies]
base = "0.13.5"
uuid = "https://github.com/aviate-labs/uuid.mo#v0.2.0"

[canisters.api_canister]
main = "src/Main.mo"
args = ["--enhanced-orthogonal-persistence"]
